openapi: 3.1.0
info:
  title: Helpcenter IM_Message API
  version: 1.0.0
tags:
- name: IM_Message
paths:
  /api/v1/im/channels/{channelId}/initiateSession:
    post:
      tags:
      - IM_Message
      summary: Initiate Session
      description: This API initiates a session with a template message
      operationId: initiateSessionUsingTemplate
      parameters:
      - name: channelId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type:
          - string
          - 'null'
          - integer
          format: int64
          pattern: ([0-9]+)
      - $ref: ./Common.json#/components/parameters/orgId
      requestBody:
        $ref: '#/components/requestBodies/initiateSessionUsingTemplate'
      responses:
        '422':
          $ref: ./Common.json#/components/responses/multipleUnprocessEntityResponse
        '200':
          $ref: '#/components/responses/getMessage_listView'
        '403':
          $ref: ./Common.json#/components/responses/forbiddenErrorResponse
      security:
      - iam-oauth2-schema:
        - Desk.InstantMessages.CREATE
      x-audience:
      - external-public
  /api/v1/channels/{channel_id}/photo:
    post:
      tags:
      - IM_Message
      summary: Update Channel logo
      description: This API updates the logo for the given channel. Logo of SYSTEM channels cannot be updated.
      operationId: uploadChannelPhoto
      parameters:
      - name: channel_id
        in: path
        description: ''
        required: true
        style: simple
        explode: false
        schema:
          type:
          - string
          - 'null'
          description: ''
          maxLength: 100
          minLength: 0
          pattern: ([a-zA-Z0-9_\-]+)
      - $ref: ./Common.json#/components/parameters/orgId
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                  description: ''
              required:
              - photo
      responses:
        '422':
          $ref: ./Common.json#/components/responses/multipleUnprocessEntityResponse
        '200':
          $ref: ./Common.json#/components/responses/emptyResponse
      security:
      - iam-oauth2-schema:
        - Desk.basic.CREATE
      x-audience:
      - external-public
components:
  requestBodies:
    initiateSessionUsingTemplate:
      content:
        application/json:
          schema:
            type:
            - 'null'
            - object
            additionalProperties: false
            properties:
              receiverId:
                type:
                - string
                - 'null'
                description: ID to which Message Has to be sent
                maxLength: 100
                minLength: 0
              receiverType:
                type:
                - string
                - 'null'
                description: Specifies receiverID type. Allowed value @PHONENUMBER@
                enum:
                - PHONENUMBER
                maxLength: 100
                minLength: 0
              meta:
                $ref: ./IM_Message.json#/components/schemas/messageMetaArray
              cannedMessageId:
                type:
                - string
                - 'null'
                - integer
                format: int64
                description: TemplateMessageId to send that template
                pattern: ([0-9]+)
              language:
                type:
                - string
                - 'null'
                description: Language of Translation. Enter this input in ISO language code. For example @en@, @fr@, @de@, @bn@, @ta@ etc
                maxLength: 100
                minLength: 0
                pattern: af|sq|ar|az|bn|bg|ca|zh_CN|zh_HK|zh_TW|hr|cs|da|nl|en_GB|en_US|et|fil|fi|fr|ka|de|el|gu|ha|he|hi|hu|id|ga|it|ja|kn|kk|rw_RW|ko|ky_KG|lo|lv|lt|mk|ms|ml|mr|nb|fa|pl|pt_BR|pt_PT|pa|ro|ru|sr|sk|sl|es|es_AR|es_ES|es_MX|sw|sv|ta|te|th|tr|uk|ur|uz|vi|zu|en
              message:
                type:
                - string
                - 'null'
                description: Content of the message
                maxLength: 65535
                minLength: 0
            required:
            - cannedMessageId
            - language
            - message
            - receiverId
            - receiverType
          examples:
            Valid requestBody Definitions:
              value:
                receiverId: '109000000002003'
                receiverType: PHONENUMBER
                cannedMessageId: '3942000001074175'
                language: en
                message: Welcome to Tasty Bakery. What would you like to eat?
  responses:
    getMessage_listView:
      description: getMessage_listView template definitions
      content:
        application/json:
          schema:
            additionalProperties: false
            allOf:
            - $ref: ./IM_Message.json#/components/schemas/getMessage_listview_main
            - type:
              - 'null'
              - object
              properties:
                replyToMessage:
                  $ref: ./IM_Message.json#/components/schemas/replyToMessage
              required:
              - replyToMessage
          examples:
            Valid responses Definitions:
              value: null
  securitySchemes:
    iam-oauth2-schema:
      $ref: ./Common.json#/components/securitySchemes/iam-oauth2-schema
x-entity: Helpcenter
